SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE VIEW [1001].[Collection Games]
AS
SELECT        COUNT(DISTINCT Title) AS Games
FROM            Collection.Games
WHERE        ([1001] = 1)
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
