SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE VIEW [1001].[Movies]
AS
SELECT COUNT(subquery._1001) + 2 as [Movies]  -- Riget, Dekalog
FROM (SELECT DISTINCT(Imdb), _1001 FROM dbo.Movies) as subquery
WHERE subquery._1001 = 1
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
