SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE VIEW [1001].[Books]
AS
SELECT        COUNT(_1001) + 1 AS Books -- Watchmen
FROM            dbo.Books
WHERE        _1001 = 1
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
