//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Controller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
        ///1,tt0000417,2013-10-01,2013-10-01,,Le voyage dans la lune,https://www.imdb.com/title/tt0000417/,short,8.2,13,1902,&quot;Short, Action, Adventure, Comedy, Fantasy, Sci-Fi&quot;,43317,1902-09-01,Georges Méliès
        ///2,tt0000439,2013-10-01,2013-10-01,,The Great Train Robbery,https://www.imdb.com/title/tt0000439/,short,7.3,11,1903,&quot;Short, Action, Crime, Western&quot;,17064,1903-12-07,Edwin S. Port [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1001_Movies_You_Must_See_Before_You_Die__2020_Edit {
            get {
                return ResourceManager.GetString("_1001_Movies_You_Must_See_Before_You_Die__2020_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
        ///1,tt0040053,2015-11-27,2015-11-27,,Toast of the Town,https://www.imdb.com/title/tt0040053/,tvSeries,7.8,60,1948,&quot;Comedy, Music&quot;,1121,1948-06-20,
        ///2,tt0041030,2015-11-27,2015-11-27,,Hopalong Cassidy,https://www.imdb.com/title/tt0041030/,tvSeries,7.9,60,1952,Western,289,1952-09-19,
        ///3,tt0041038,2015-11-27,2015-11-27,,The Lone Ranger,https://www.imdb.com/title/tt0041038/,tvSeri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1001_TV_Shows_You_Must_Watch_Before_you_Die {
            get {
                return ResourceManager.GetString("_1001_TV_Shows_You_Must_Watch_Before_you_Die", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainConnectionString {
            get {
                return ResourceManager.GetString("MainConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
        ///1,tt0033467,2021-01-27,2021-01-27,,Citizen Kane,https://www.imdb.com/title/tt0033467/,movie,8.3,119,1941,&quot;Drama, Mystery&quot;,405520,1941-05-01,Orson Welles
        ///2,tt0052357,2021-01-27,2021-01-27,,Vertigo,https://www.imdb.com/title/tt0052357/,movie,8.3,128,1958,&quot;Mystery, Romance, Thriller&quot;,366157,1958-05-09,Alfred Hitchcock
        ///3,tt0062622,2021-01-27,2021-01-27,,2001: A Space Odyssey,h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TSPDT__They_Shoot_Pictures__Don_t_They__1_000_Grea {
            get {
                return ResourceManager.GetString("TSPDT__They_Shoot_Pictures__Don_t_They__1_000_Grea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
        ///1,tt0118694,2020-02-22,2020-02-22,,Fa yeung nin wah,https://www.imdb.com/title/tt0118694/,movie,8.1,98,2000,&quot;Drama, Romance&quot;,125396,2000-05-20,Kar-Wai Wong
        ///2,tt0166924,2020-02-22,2020-02-22,,Mulholland Dr.,https://www.imdb.com/title/tt0166924/,movie,7.9,147,2001,&quot;Drama, Mystery, Thriller&quot;,323749,2001-05-16,David Lynch
        ///3,tt0244316,2020-02-22,2020-02-22,,Yi yi,https://www.im [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TSPDT__They_Shoot_Pictures_21st_Century_Top_1000_F {
            get {
                return ResourceManager.GetString("TSPDT__They_Shoot_Pictures_21st_Century_Top_1000_F", resourceCulture);
            }
        }
    }
}
