// <Auto-Generated>
// This is here so CodeMaid doesn't reorganize this document
// </Auto-Generated>

using System.ComponentModel;

namespace Model.Grid
{
    public class CollectionGames
    {
        [Browsable(false)]
        public int ID { get; set; }
        public string Title { get; set; }
        public int Year { get; set; }
        public string Platform { get; set; }
        public int HLTB { get; set; }
        public string Freshnes { get; set; }
    }
}