// <Auto-Generated>
// This is here so CodeMaid doesn't reorganize this document
// </Auto-Generated>

using System.ComponentModel;

namespace Model
{
    public class DnDEventGrid
    {
        [Browsable(false)]
        public int ID { get; set; }

        [Browsable(false)]
        public int ItemID { get; set; }
        public string Summary { get; set; }
        public int? Hours { get; set; }
        public string Location { get; set; }
        public int? Level { get; set; }

    }
}