// <Auto-Generated>
// This is here so CodeMaid doesn't reorganize this document
// </Auto-Generated>

using System.ComponentModel;

namespace Model.Grid
{
	public class IgdbList
	{
		[Browsable(false)]
		public int Igdb { get; set; }
		public string Title { get; set; }
		public int? Year { get; set; }
		public bool _1001 { get; set; }
		public bool Owned { get; set; }
	}
}