// <Auto-Generated>
// This is here so CodeMaid doesn't reorganize this document
// </Auto-Generated>

using System.ComponentModel;

namespace Model.Grid
{
	public class ImdbList:IImdb
	{
		[Browsable(false)]
		public string Imdb { get; set; }
		public string Title { get; set; }
		public string Director { get; set; }
		public int? Year { get; set; }
		public int? Runtime { get; set; }
		public int? Votes { get; set; }
		public float? Rating { get; set; }
		public bool _1001 { get; set; }
	}
}