// <Auto-Generated>
// This is here so CodeMaid doesn't reorganize this document
// </Auto-Generated>

using System.ComponentModel;

namespace Model.Grid
{
    public class LinkGrid
    {
        [Browsable(false)]
        public int ID { get; set; }
        public string Title { get; set; }
        public int Count { get; set; }
    }
}