// <Auto-Generated>
// This is here so CodeMaid doesn't reorganize this document
// </Auto-Generated>

using System.ComponentModel;

namespace Model.Grid
{
    public class MovieCollection
    {
        [Browsable(false)]
        public int ID { get; set; }
        public string Title { get; set; }
        public string Director { get; set; }
        public int? Year { get; set; }
        public string Format { get; set; }
    }
}