// <Auto-Generated>
// This is here so CodeMaid doesn't reorganize this document
// </Auto-Generated>

using System.ComponentModel;

namespace Model
{
    public class PeopleGrid
    {
        [Browsable(false)]
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}